import { v4 as uuidv4 } from "uuid";

export const chatHomePrompts = [
  {
    id: uuidv4(),
    content: "Do you offer free consultation?.",
  },
  {
    id: uuidv4(),
    content: "What services do you offer?",
  },
  {
    id: uuidv4(),
    content: "What payment methods do you accept?",
  },
];

export const questions = [
  "Do you have experience customizing existing CRMs like Salesforce or building custom CRMs?",
  "Do you have experience building custom CMS solutions or integrating with existing platforms like WordPress or Drupal?",
  "Can you ensure the CMS is user-friendly for content creators within our agency?",
  "Do you have an understanding of and experience with cutting-edge technologies like AI-powered personalization, chatbots, or augmented reality (AR)?",
  "Can you seamlessly integrate your developed software with our existing technology stack? How will you achieve this?",
  "Can the software you build scale to accommodate our growing needs?",
  "What kind of support and maintenance services do you offer after the software is developed?",
  "Do you offer training and support to the team on how to use the developed software effectively?",
  "What development process do you follow?",
  "Do you have a data-driven approach to development, ensuring the software aligns with our overall goals and key performance indicators (KPIs)?",
  "Can you provide examples of past projects you’ve done for clients in our industry? Do you have references you can connect us with?",
  "Do you have a dedicated project manager who will handle communication and ensure the project stays on track?",
  "How often will you communicate project updates and how will you handle feedback?",
  "Do you deal with sensitive client data? How will you ensure the security of their data throughout the process?",
  "How do you ensure transparency and keep us informed throughout the process?",
  "Do you utilize project tracking tools that provide real-time visibility into progress, timelines, and potential roadblocks?",
  "Will we have access to project tracking tools?",
  "What is your frequency for providing project status reports? What information will these reports typically include?",
  "How do you manage communication with various stakeholders within our agency, including project managers, designers etc?",
  "How do you incorporate client feedback into the development process?",
  "What is your process for handling revisions and change requests?",
  "Is there a limit on the number of revisions per module? What will happen if we exceed them?",
  "What communication channels do you prefer to use (e.g., email, project management tools, video conferencing)?",
  "How do you manage scope creep - the tendency for project requirements to change mid-development?",
  "What steps do you take to ensure the project stays on budget and timeline?",
  "What is your approach to identifying and mitigating potential project risks?",
  "How will you keep us informed of any potential roadblocks?",
  "Do you have contingency plans in place to address unexpected challenges or delays?",
  "Do you offer fixed-price quotes for projects, or do you bill by the hour?",
  "What factors influence your pricing model selection?",
  "Can you provide a breakdown of the costs involved in a project?",
  "How do you handle changes to the project scope after the initial agreement?",
  "What is the process for estimating and communicating the cost of additional features or revisions?",
  "What is your typical payment schedule for projects?",
  "Do you require upfront deposits or milestone payments?",
  "What payment methods do you accept?",
  "Do you offer any flexible billing options, such as retainer agreements or performance-based pricing?",
  "Can you provide a ballpark estimate for developing our specific software needs?",
  "Do you offer any services to help them optimize our budget for the project?",
  "Can you suggest ways to prioritize features or functionalities to stay within our budget constraints?",
  "How much time do you typically allocate for the initial discovery and planning phase before development begins?",
  "Do you offer a phased development approach, allowing for the delivery of core functionalities first, followed by additional features in subsequent phases?",
  "How do you prioritize features and functionalities within the project timeline?",
  "Do you use an iterative development process that allows for ongoing feedback and adjustments to the timeline as needed?",
  "Can you share past examples of projects where you successfully met or exceeded deadlines?",
  "What was your process for ensuring on-time delivery?",
  "How do you identify and manage potential risks that could impact the project timeline?",
  "What is your plan for communicating and addressing any delays that may arise?",
  "How do changes to the project scope or requirements affect the timeline?",
  "Can you provide an estimate of how additional features or revisions might impact the delivery date?",
  "I want to know more about X service.",
  "I want to know the price of X service.",
  "Will you be available in X timezone?",
  "I have a project in mind. When can I get in touch with your sales representative?",
  "Do you offer free consultation?",
  "What is your turnaround time for projects?",
  "How can I contact you to discuss my project further?",
  "What is your experience with X industry?",
  "What services do you offer?",
  "Can I get your rate card?",
];
