export const questions = [
  "Who are SDU?",
  "Why should I work with you?",
  "What do you mean by FORD?",
  "How big is SDU?",
  "Who should I contact for Direct Taxes?",
  "Who should I contact for Indirect Taxes?",
  "Who should I contact for Business Consulting?",
  "Who should I contact for a Statutory Audit?",
  "Who should I contact for Risk & Assurance?",
  "What does SDU specialize in?",
  "What do you specialize in?",
  "What services do you offer?",
  "Give me a brief about your services.",
  "Do you have any openings?",
  "Where are you located?",
  "How can I contact you?",
];
